disabled_rules:
- opening_brace # Conflicts with default SwiftFormat rule https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#wrapmultilinestatementbraces
- trailing_comma # Conflicts with default SwiftFormat rule https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#trailingCommas

line_length:
  warning: 160
  error: 160
  ignores_comments: true

nesting:
  type_level: 3
  function_level: 3

excluded:
- Pods

# Upgrade default rules to error, instead of warning
# Make error values equal to the warning values

blanket_disable_command:
  severity: error
block_based_kvo:
  severity: error
class_delegate_protocol:
  severity: error
closing_brace:
  severity: error
closure_parameter_position:
  severity: error
colon:
  severity: error
comma:
  severity: error
comment_spacing:
  severity: error
compiler_protocol_init:
  severity: error
computed_accessors_order:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  warning: 20
  error: 20
  ignores_case_statements: true
deployment_target:
  severity: error
discouraged_direct_init:
  severity: error
duplicate_imports:
  severity: error
duplicated_key_in_dictionary_literal:
  severity: error
empty_enum_arguments:
  severity: error
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
file_length:
  error: 400
for_where:
  severity: error
function_body_length:
  warning: 100
  error: 100
function_parameter_count:
  error: 5
generic_type_name:
  min_length:
    error: 1
  max_length:
    error: 20
identifier_name:
  min_length:
    warning: 1
  max_length:
    error: 40
implicit_getter:
  severity: error
inclusive_language:
  severity: error
invalid_swiftlint_command:
  severity: error
is_disjoint:
  severity: error
large_tuple:
  error: 2
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
mark:
  severity: error
multiple_closures_with_trailing_closure:
  severity: error
no_fallthrough_only:
  severity: error
no_space_in_method_call:
  severity: error
notification_center_detachment:
  severity: error
ns_number_init_as_function_reference:
  severity: error
nsobject_prefer_isequal:
  severity: error
operator_whitespace:
  severity: error
orphaned_doc_comment:
  severity: error
private_over_fileprivate:
  severity: error
private_unit_test:
  severity: error
protocol_property_accessors_order:
  severity: error
reduce_boolean:
  severity: error
redundant_discardable_let:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
self_in_property_initialization:
  severity: error
statement_position:
  severity: error
superfluous_disable_command:
  severity: error
switch_case_alignment:
  severity: error
syntactic_sugar:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_body_length:
  error: 250
type_name:
  min_length:
    warning: 1
  max_length:
    error: 40
unavailable_condition:
  severity: error
unneeded_break_in_switch:
  severity: error
unused_closure_parameter:
  severity: error
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: error
unused_optional_binding:
  severity: error
unused_setter_value:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_function_in_ternary:
  severity: error
void_return:
  severity: error
xctfail_message:
  severity: error
